#!/bin/sh

cd ${0%/*} || exit 1                        # Run from this directory
. /opt/OpenFOAM/OpenFOAM-v1912/bin/tools/CleanFunctions  # Tutorial clean functions
cleanCase0


# this was the original allclean script for icofoam cases
#keepCases="cavity cavityGrade cavityClipped"cd ..
#loseCases="cavityFine cavityHighRe"

#for caseName in $keepCases
#do
#    ( cd $caseName && foamCleanTutorials )
#done

#for caseName in $loseCases
#do
#    removeCase $caseName
#done$Wm

#------------------------------------------------------------------------------
.